config/routes.rb
Rails.application.routes.draw do

  resources :annual_meetings

 resources :users
 resources :my_collected_votes

  resources :shareholder_confirmations

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

   resources :buildings

end

app/models/my_collected_vote.rb
# == Schema Information
#
# Table name: my_collected_votes
#
#  id              :integer          not null, primary key
#  votes_collected :integer
#  building_id     :integer
#  user_id         :integer
#  year            :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class MyCollectedVote < ActiveRecord::Base
  # belongs_to :user

   def self.update_total_vote_count
    #get count from all my_collected votes for all buildings
    total_count = 0

    self.all.each do |vote_collector|
      total_count += vote_collector.votes_collected
    end

    total_count
    
  end

  def self.vote_count_by_building

    # proxy_votes_by_building = [
    #   {:building_id => 1, :name => "365 Clinton", :building_votes => 22}
    # ]
    # currently ignoring year

    proxy_votes_by_building = []
    collected_votes = []
    buildings = Building.all
    collected_votes = self.all

    # create array of hashes with building id and name
    proxy_votes_by_building = buildings.collect{|building| {:building_id => building.id, :building_name => building.name}}

    # for each building
    proxy_votes_by_building.each do |building|

      building[:building_votes] = 0

      #find all vote collectors for this building
      vote_collectors = self.where :building_id => building[:building_id]

      vote_collectors.each do |vote_collector|
        building[:building_votes] += vote_collector.votes_collected
      end


      # sum up all votes from all vote collectors for each building 
      # building[:building_votes] = vote_collectors.collect{|vote_collector|{ vote_collector.votes_collected}}
    end

    proxy_votes_by_building

  end
end

app/controllers/my_collected_votes_controller.rb
class MyCollectedVotesController < ApplicationController
  before_action :set_my_collected_vote, only: [:show, :edit, :update, :destroy]

  # GET /my_collected_votes
  # GET /my_collected_votes.json
  def index
    @my_collected_votes = MyCollectedVote.all
  end

  # GET /my_collected_votes/1
  # GET /my_collected_votes/1.json
  def show
  end

  # GET /my_collected_votes/new
  def new
    @my_collected_vote = MyCollectedVote.new
  end

  # GET /my_collected_votes/1/edit
  def edit
  end

  # POST /my_collected_votes
  # POST /my_collected_votes.json
  def create
    @my_collected_vote = MyCollectedVote.new(my_collected_vote_params)

    respond_to do |format|
      if @my_collected_vote.save

        #set proxy_vote.total_count for this year to += this vote count for this year

        #set proxy_vote.building_count for each building to += this vote count for this year
        

        format.html { redirect_to @my_collected_vote, notice: 'My collected vote was successfully created.' }
        format.json { render :show, status: :created, location: @my_collected_vote }
      else
        format.html { render :new }
        format.json { render json: @my_collected_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_collected_votes/1
  # PATCH/PUT /my_collected_votes/1.json
  def update
    respond_to do |format|
      if @my_collected_vote.update(my_collected_vote_params)
        format.html { redirect_to @my_collected_vote, notice: 'My collected vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_collected_vote }
      else
        format.html { render :edit }
        format.json { render json: @my_collected_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_collected_votes/1
  # DELETE /my_collected_votes/1.json
  def destroy
    @my_collected_vote.destroy
    respond_to do |format|
      format.html { redirect_to my_collected_votes_url, notice: 'My collected vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_collected_vote
      @my_collected_vote = MyCollectedVote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_collected_vote_params
      params.require(:my_collected_vote).permit(:votes_collected, :building_id, :user_id, :year)
    end
end

app/helpers/my_collected_votes_helper.rb
module MyCollectedVotesHelper
end

app/views/my_collected_votes/_form.html.erb
<%= form_for(@my_collected_vote) do |f| %>
  <% if @my_collected_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_collected_vote.errors.count, "error") %> prohibited this my_collected_vote from being saved:</h2>

      <ul>
      <% @my_collected_vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :votes_collected, "Total Votes I've Collected:" %><br>
    <%= f.number_field :votes_collected, :placeholder => "None yet..." %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
     <%= f.collection_select :building_id, Building.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label "User" %><br>
      <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year, :value => Time.now.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_collected_votes/edit.html.erb
<h1>Editing my_collected_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_collected_vote %> |
<%= link_to 'Back', my_collected_votes_path %>

app/views/my_collected_votes/index.html.erb
<h1>Listing my_collected_votes</h1>

<table>
  <thead>
    <tr>
      <th>Votes collected</th>
      <th>Building</th>
      <th>User</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_collected_votes.each do |my_collected_vote| %>
      <tr>
        <td><%= my_collected_vote.votes_collected %></td>
        <td><%= my_collected_vote.building_id %></td>
        <td><%= my_collected_vote.user_id %></td>
        <td><%= my_collected_vote.year %></td>
        <td><%= link_to 'Show', my_collected_vote %></td>
        <td><%= link_to 'Edit', edit_my_collected_vote_path(my_collected_vote) %></td>
        <td><%= link_to 'Destroy', my_collected_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My collected vote', new_my_collected_vote_path %>

app/views/my_collected_votes/new.html.erb
<h1>New my_collected_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', my_collected_votes_path %>

app/views/my_collected_votes/show.html.erb
<p>
  <strong>Total Votes I've Collected:</strong>
  <%= @my_collected_vote.votes_collected %>
</p>

<p>
  <strong>Building:</strong>
  <%= Building.find(@my_collected_vote.building_id).name %>
</p>

<p>
  <strong>User:</strong>
  <%= User.find(@my_collected_vote.user_id).nickname %>
</p>

<p>
  <strong>Year:</strong>
  <%= @my_collected_vote.year %>
</p>

<%= link_to 'Edit', edit_my_collected_vote_path(@my_collected_vote) %> |
<%= link_to 'Back', my_collected_votes_path %>